package com.toggle.entity;

public enum BusinessVerificationStatus {
    NOT_STARTED,
    AUTO_VERIFICATION_PENDING,
    AUTO_VERIFIED,
    AUTO_VERIFICATION_UNAVAILABLE,
    AUTO_VERIFICATION_FAILED,
    MANUAL_VERIFICATION_REQUIRED,
    MANUAL_VERIFIED,
    MANUAL_VERIFICATION_FAILED
}
